recipe: default.v1


assistant_id: 20250516-113330-broad-cloverleaf

language: it_core_news_sm


pipeline:
- name: SpacyNLP
  model: "it_core_news_sm"
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.8
  ambiguity_threshold: 0.1
- name: EntitySynonymMapper
- name: RegexFeaturizer


policies:
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_llm_fallback"  
  enable_fallback_prediction: true
- name: MemoizationPolicy
- name: TEDPolicy